apiVersion: v1
kind: Secret
metadata:
  name: regcred
data:
  .dockerconfigjson: DOCKER_CONFIG
type: kubernetes.io/dockerconfigjson

---

apiVersion: v1
kind: Service
metadata:
  name: flask-api
  namespace: myflix
  labels:
    backend: flaskapi-backend
spec:
  selector:
    backend: flaskapi-backend
  ports:
  - port: 5000
    targetPort: 5000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapi-deployment
  namespace: myflix
spec:
  replicas: 1
  selector:
    matchLabels:
      backend: flaskapi-backend
  template:
    metadata:
      name: flaskpods
      namespace: myflix
      labels:
        backend: flaskapi-backend
    spec:
      containers:
      - name: flaskapi
        image: stuflo/myflix:flask-prod
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
      imagePullSecrets:
      - name: regcred