FROM python:3.7.15-alpine3.17

RUN apk add build-base
RUN apk add --no-cache openssl-dev libffi-dev

RUN pip3 install pipenv

ENV FLASK_APP MyFlix_API.app
ENV FLASK_DEBUG 1

ENV MONGO_URI mongodb://root:password123@mongo/myflix?authSource=admin

WORKDIR /app

COPY . /app
RUN pipenv install --system --ignore-pipfile

CMD ["gunicorn", "--bind", "0.0.0.0:5000", "MyFlix_API.production:app"]
