apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: myflix
  labels:
    db: mongo
spec:
  selector:
    db: mongo
  ports:
  - port: 27017
    targetPort: 27017

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-mongo
  namespace: myflix
  labels: 
    db: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      db: mongo
  template:
    metadata:
      name: db-pods
      namespace: myflix
      labels:
        db: mongo
    spec:
      containers:
      - name: db-containers
        image: mongo
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-pvc
          mountPath: /data/db
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: root
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: password123
      volumes:
      - name: mongo-pvc
        persistentVolumeClaim:
          claimName: mongo-pvc